import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import Section1 from "../components/Section1";
import Section2 from "../components/Section2";
import Section3 from "../components/Section3";
import Section4 from "../components/Section4";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Blog App Using NextJS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Section1 />
          <Section2 />
          <Section3 />
          <Section4 />
        </main>
      </div>
    </Layout>
  );
}
